### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by sobolevn** [Miserlou/JonesComplexity#20]
I guess that `py3.6` is supported, but it is not clearly stated neither in `setup.py` nor `.travis.yml`.

I guess, that it is not a big problem and I will send a PR shortly.

**Comment by Miserlou** [comment]
I try to write 3.6 compatible code, but I still default to 2.7. If there are aspects which do not work with 3.6, that should be fixed.

**Comment by sobolevn** [comment]
Closed via https://github.com/Miserlou/JonesComplexity/pull/27
