### ISSUE TITLE
Drop legacy versions support

### ISSUE THREAD

**Issue by sobolevn** [Miserlou/JonesComplexity#24]
That's a mostly question to @Miserlou.
I have seen some remarks about `python2.5` in the source code.

Can I drop support of it? Since `python2.5` is dead for a long time now.

And so is `python3.3` and `python3.4`.
1. https://www.python.org/dev/peps/pep-0398/
2. https://www.python.org/dev/peps/pep-0429/

**Comment by Miserlou** [comment]
2.5 can die, 2.7 and 3.5+ (even 3.6 for all I care) should be supported though.
